---
title: '%'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(Seurat)
library(cowplot)
library(patchwork)
library(ggpubr)
library(stringr)
library(tidyverse)

```

1. WT only
2. analysis
3. WT and MUT
4. analysis

#2 cluster annotation study using table 2 here exp from paper La Mano et al
#for seurat
```{r}


a=read.csv("Z:\\16-Our Papers\\In Preparation\\LRRK2_scRNA\\35&70D\\Figures\\Figure 2 Cell clusters\\Originals\\Data\\LaMano\\markers.csv", header = T, row.names = 1)
fix(a)

#add numbers so that no duplicates
seur=read.csv("Z:\\16-Our Papers\\In Preparation\\LRRK2_scRNA\\35&70D\\Figures\\Figure 2 Cell clusters\\Originals\\Data\\Cell_cluster_markers_integrated_object_EM_MOs.csv", header = T, row.names= 1)
fix(seur)



BasalGenes = a[a$Basal == 1,]
#fix(BasalGenes)
BG=as.vector(rownames(BasalGenes))

#fix(BG)
#write.csv(BasalGenes$Genes, file = "Basal.csv")

for (i in 1:3670) {
if ((row.names(seur[i,]) %in% BG) == TRUE) {seur$Basal[i] <- "Basal" }}
#seur$Basal[5]
#t=row.names(seur[1,])
#k=row.names(seur[,]) %in% BG 
#row.names(seur[5,]) %in% BG == T

# do this for all

hEndoGenes = a[a$hEndo == 1,]
hEndo= as.vector(rownames(hEndoGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hEndo) == TRUE) {seur$hEndo[i] <- "hEndo" }}


hPericGenes = a[a$hPeric == 1,]
Peri=as.vector(rownames(hPericGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% Peri) == TRUE) {seur$hPeric[i] <- "hPeric" }}

hMglGenes = a[a$hMgl == 1,]
hMg1=as.vector(rownames(hMglGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hMg1) == TRUE) {seur$hMgl[i] <- "hMgl" }}


hOPCGenes = a[a$hOPC == 1,]
hOPC=as.vector(rownames(hOPCGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hOPC) == TRUE) {seur$hOPC[i] <- "hOPC" }}

hRgl2cGenes = a[a$hRgl2c == 1,]
hRgl2c=as.vector(rownames(hRgl2cGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hRgl2c) == TRUE) {seur$hRgl2c[i] <- "hRgl2c" }}


hRgl2bGenes = a[a$hRgl2b == 1,]
hRgl2b=as.vector(rownames(hRgl2bGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hRgl2b) == TRUE) {seur$hRgl2b[i] <- "hRgl2b" }}


hRgl2aGenes = a[a$hRgl2a == 1,]
hRgl2a=as.vector(rownames(hRgl2aGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in%hRgl2a) == TRUE) {seur$hRgl2a[i] <- "hRgl2a" }}

hRgl3Genes = a[a$hRgl3 == 1,]
hRgl3=as.vector(rownames(hRgl3Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hRgl3) == TRUE) {seur$hRgl3[i] <- "hRgl3" }}

hRgl1Genes = a[a$hRgl1 == 1,]
hRgl1=as.vector(rownames(hRgl1Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hRgl1) == TRUE) {seur$hRgl1[i] <- "hRgl1" }}

hProgMGenes = a[a$hProgM == 1,]
hProgM=as.vector(rownames(hProgMGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hProgM) == TRUE) {seur$hProgM[i] <- "hProgM" }}

hProgBPGenes = a[a$hProgBP == 1,]
hProgBP=as.vector(rownames(hProgBPGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hProgBP) == TRUE) {seur$hProgBP[i] <- "hProgBP" }}


hProgFPLGenes = a[a$hProgFPL == 1,]
hProgFPL=as.vector(rownames(hProgFPLGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hProgFPL) == TRUE) {seur$hProgFPL[i] <- "hProgFPL" }}


hProgFPMGenes = a[a$hProgFPM == 1,]
hProgFPM=as.vector(rownames(hProgFPMGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hProgFPM) == TRUE) {seur$hProgFPM[i] <- "hProgFPM" }}


hNProgGenes = a[a$hNProg == 1,]
hNProg=as.vector(rownames(hNProgGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hNProg) == TRUE) {seur$hNProg[i] <- "hNProg" }}

hNbMGenes = a[a$hNbM == 1,]
hNbM=as.vector(rownames(hNbMGenes ))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hNbM) == TRUE) {seur$hNbM[i] <- "hNbM" }}

hNbML1Genes = a[a$hNbML1 == 1,]
hNbML1=as.vector(rownames(hNbML1Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hNbML1) == TRUE) {seur$hNbML1[i] <- "hNbML1" }}


hRNGenes = a[a$hRN == 1,]
hRN=as.vector(rownames(hRNGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hRN) == TRUE) {seur$hRN[i] <- "hRN" }}

hNbML5Genes = a[a$hNbML5 == 1,]
hNbML5=as.vector(rownames(hNbML5Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hNbML5) == TRUE) {seur$hNbML5[i] <- "hNbML5" }}


hDA0Genes = a[a$hDA0 == 1,]
hDA0=as.vector(rownames(hDA0Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hDA0) == TRUE) {seur$hDA0[i] <- "hDA0" }}

hDA1Genes = a[a$hDA1 == 1,]
hDA1=as.vector(rownames(hDA1Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hDA1) == TRUE) {seur$hDA1[i] <- "hDA1" }}

hDA2Genes = a[a$hDA2 == 1,]
hDA2=as.vector(rownames(hDA2Genes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hDA2) == TRUE) {seur$hDA2[i] <- "hDA2" }}


hNbGabaGenes = a[a$	hNbGaba == 1,]
hNbGaba=as.vector(rownames(hNbGabaGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hNbGaba) == TRUE) {seur$hNbGaba[i] <- "hNbGaba" }}


hGabaGenes = a[a$	hGaba == 1,]
hGaba=as.vector(rownames(hGabaGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hGaba) == TRUE) {seur$hGaba[i] <- "hGaba" }}


hSertGenes = a[a$hSert == 1,]
hSert=as.vector(rownames(hSertGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hSert) == TRUE) {seur$hSert[i] <- "hSert" }}


hOMTNGenes = a[a$hOMTN== 1,]
hOMTN=as.vector(rownames(hOMTNGenes))
for (i in 1:3670) {
if ((row.names(seur[i,]) %in% hOMTN) == TRUE) {seur$hOMTN[i] <- "hOMTN" }}


write.csv(seur, file = "annotatedclustersManoall4.csv")
```


```{r}
# take care of duplicates! replace by genelist with duplicates

# 1. take seurat file, format duplicative genename cells to text, order a-z copy into annotatedclusters, ordered the same way. save as dupli. replace Genes if fix, if shows sth else.

g=read.csv("C:/Users/sarah.nickels/Desktop/data/markers_integanalysis_OrgMutWTEmb_wdupli_Manoall4.csv", header = T )


fix(g)

library(dplyr)

d=duplicated(g$Genes[])
d[2]
for (n in 3:length(g)) {
  #replace length vector
for (i in 1:3669){
            if (d[i] == TRUE) { g[i,n] <- as.character(g[i-1,n]) }
}
  }

write.csv(g, file = "annotatedclusterswithduplicatesall4.csv")

```


```{r}
# seperate into clusters

g=read.csv("C:/Users/sarah.nickels/Desktop/data/annotatedclusterswithduplicatesall4.csv", header = T )


one = filter(g, g$cluster == 1)
two= filter(g, g$cluster == 2)
three= filter(g, g$cluster == 3)
four= filter(g, g$cluster == 4)
five= filter(g, g$cluster == 5)
six= filter(g, g$cluster == 6)
seven= filter(g, g$cluster == 7)
eight= filter(g, g$cluster == 8)
nine= filter(g, g$cluster == 9)
zero= filter(g, g$cluster == 0)

  
o=length(one$Genes)

ob=length(which(one$Basal == "Basal"))
oe=length(which(one$hEndo == "hEndo"))
op=length(which(one$	hPeric == "hPeric"))
om=length(which(one$hMgl == "hMgl"))
oo=length(which(one$	hOPC == "	hOPC"))

orc=length(which(one$	hRgl2c == "	hRgl2c"))
orb=length(which(one$hRgl2b == "hRgl2b"))
or=length(which(one$hRgl3 == "hRgl3"))
ora=length(which(one$	hRgl2a == "hRgl2a"))
orr=length(which(one$hRgl1 == "hRgl1"))

opm=length(which(one$hProgM == "hProgM"))
opbp=length(which(one$	hProgB == "hProgBP"))
opfpm=length(which(one$hProgFPM	 == "hProgFPM	"))
opfpl=length(which(one$hProgFPL == "hProgFPL"))
opn=length(which(one$	hNProg== "hNProg"))

on=length(which(one$	hNbM == "hNbM"))
onl=length(which(one$	hNbML1 == "hNbML1"))
orn=length(which(one$	hRN == "hRN"))
onll=length(which(one$hNbML5 == "hNbML5"))

odo=length(which(one$hDA0 == "hDA0"))
od=length(which(one$hDA1 == "hDA1"))
odd=length(which(one$hDA2 == "hDA2"))
og=length(which(one$hNbGaba == "hNbGaba"))
ogb=length(which(one$hGaba == "hGaba"))
ogba=length(which(one$hSert == "hSert"))
oomt=length(which(one$hOMTN == "hOMTN"))


t=length(two$Genes)

tb=length(which(two$Basal == "Basal"))
te=length(which(two$hEndo == "hEndo"))
tp=length(which(two$	hPeric == "hPeric"))
tm=length(which(two$hMgl == "hMgl"))
to=length(which(two$	hOPC == "	hOPC"))

trc=length(which(two$	hRgl2c == "	hRgl2c"))
trb=length(which(two$hRgl2b == "hRgl2b"))
tr=length(which(two$hRgl3 == "hRgl3"))
tra=length(which(two$	hRgl2a == "hRgl2a"))
trr=length(which(two$hRgl1 == "hRgl1"))

tpm=length(which(two$hProgM == "hProgM"))
tpbp=length(which(two$	hProgB == "hProgBP"))
tpfpm=length(which(two$hProgFPM	 == "hProgFPM	"))
tpfpl=length(which(two$hProgFPL == "hProgFPL"))
tpn=length(which(two$	hNProg== "hNProg"))

tn=length(which(two$	hNbM == "hNbM"))
tnl=length(which(two$	hNbML1 == "hNbML1"))
trn=length(which(two$	hRN == "hRN"))
tnll=length(which(two$hNbML5 == "hNbML5"))

tdo=length(which(two$hDA0 == "hDA0"))
td=length(which(two$hDA1 == "hDA1"))
tdd=length(which(two$hDA2 == "hDA2"))
tg=length(which(two$hNbGaba == "hNbGaba"))
tgb=length(which(two$hGaba == "hGaba"))
tgba=length(which(two$hSert == "hSert"))
tomt=length(which(two$hOMTN == "hOMTN"))


  
i=length(three$Genes)

bs=length(which(three$Basal == "Basal"))
es=length(which(three$hEndo == "hEndo"))
ps=length(which(three$	hPeric == "hPeric"))
ms=length(which(three$hMgl == "hMgl"))
os=length(which(three$	hOPC == "	hOPC"))

rc=length(which(three$	hRgl2c == "	hRgl2c"))
rb=length(which(three$hRgl2b == "hRgl2b"))
rs=length(which(three$hRgl3 == "hRgl3"))
ra=length(which(three$	hRgl2a == "hRgl2a"))
rr=length(which(three$hRgl1 == "hRgl1"))

pm=length(which(three$hProgM == "hProgM"))
pbp=length(which(three$	hProgB == "hProgBP"))
pfpm=length(which(three$hProgFPM	 == "hProgFPM	"))
pfpl=length(which(three$hProgFPL == "hProgFPL"))
pn=length(which(three$	hNProg== "hNProg"))

ns=length(which(three$	hNbM == "hNbM"))
nl=length(which(three$	hNbML1 == "hNbML1"))
rn=length(which(three$	hRN == "hRN"))
nll=length(which(three$hNbML5 == "hNbML5"))

do=length(which(three$hDA0 == "hDA0"))
ds=length(which(three$hDA1 == "hDA1"))
dd=length(which(three$hDA2 == "hDA2"))
gs=length(which(three$hNbGaba == "hNbGaba"))
gb=length(which(three$hGaba == "hGaba"))
gba=length(which(three$hSert == "hSert"))
omt=length(which(three$hOMTN == "hOMTN"))

f=length(four$Genes)

fb=length(which(four$Basal == "Basal"))
fe=length(which(four$hEndo == "hEndo"))
fp=length(which(four$	hPeric == "hPeric"))
fm=length(which(four$hMgl == "hMgl"))
fo=length(which(four$	hOPC == "	hOPC"))

frc=length(which(four$	hRgl2c == "	hRgl2c"))
frb=length(which(four$hRgl2b == "hRgl2b"))
fr=length(which(four$hRgl3 == "hRgl3"))
fra=length(which(four$	hRgl2a == "hRgl2a"))
frr=length(which(four$hRgl1 == "hRgl1"))

fpm=length(which(four$hProgM == "hProgM"))
fpbp=length(which(four$	hProgB == "hProgBP"))
fpfpm=length(which(four$hProgFPM	 == "hProgFPM	"))
fpfpl=length(which(four$hProgFPL == "hProgFPL"))
fpn=length(which(four$	hNProg== "hNProg"))

fn=length(which(four$	hNbM == "hNbM"))
fnl=length(which(four$	hNbML1 == "hNbML1"))
frn=length(which(four$	hRN == "hRN"))
fnll=length(which(four$hNbML5 == "hNbML5"))

fdo=length(which(four$hDA0 == "hDA0"))
fd=length(which(four$hDA1 == "hDA1"))
fdd=length(which(four$hDA2 == "hDA2"))
fg=length(which(four$hNbGaba == "hNbGaba"))
fgb=length(which(four$hGaba == "hGaba"))
fgba=length(which(four$hSert == "hSert"))
fomt=length(which(four$hOMTN == "hOMTN"))

ff=length(five$Genes)

ffb=length(which(five$Basal == "Basal"))
ffe=length(which(five$hEndo == "hEndo"))
ffp=length(which(five$	hPeric == "hPeric"))
ffm=length(which(five$hMgl == "hMgl"))
ffo=length(which(five$	hOPC == "	hOPC"))

ffrc=length(which(five$	hRgl2c == "	hRgl2c"))
ffrb=length(which(five$hRgl2b == "hRgl2b"))
ffr=length(which(five$hRgl3 == "hRgl3"))
ffra=length(which(five$	hRgl2a == "hRgl2a"))
ffrr=length(which(five$hRgl1 == "hRgl1"))

ffpm=length(which(five$hProgM == "hProgM"))
ffpbp=length(which(five$	hProgB == "hProgBP"))
ffpfpm=length(which(five$hProgFPM	 == "hProgFPM	"))
ffpfpl=length(which(five$hProgFPL == "hProgFPL"))
ffpn=length(which(five$	hNProg== "hNProg"))

ffn=length(which(five$	hNbM == "hNbM"))
ffnl=length(which(five$	hNbML1 == "hNbML1"))
ffrn=length(which(five$	hRN == "hRN"))
ffnll=length(which(five$hNbML5 == "hNbML5"))

ffdo=length(which(five$hDA0 == "hDA0"))
ffd=length(which(five$hDA1 == "hDA1"))
ffdd=length(which(five$hDA2 == "hDA2"))
ffg=length(which(five$hNbGaba == "hNbGaba"))
ffgb=length(which(five$hGaba == "hGaba"))
ffgba=length(which(five$hSert == "hSert"))
ffomt=length(which(five$hOMTN == "hOMTN"))


s=length(six$Genes)

sb=length(which(six$Basal == "Basal"))
se=length(which(six$hEndo == "hEndo"))
sp=length(which(six$	hPeric == "hPeric"))
sm=length(which(six$hMgl == "hMgl"))
so=length(which(six$	hOPC == "	hOPC"))

src=length(which(six$	hRgl2c == "	hRgl2c"))
srb=length(which(six$hRgl2b == "hRgl2b"))
sr=length(which(six$hRgl3 == "hRgl3"))
sra=length(which(six$	hRgl2a == "hRgl2a"))
srr=length(which(six$hRgl1 == "hRgl1"))

spm=length(which(six$hProgM == "hProgM"))
spbp=length(which(six$	hProgB == "hProgBP"))
spfpm=length(which(six$hProgFPM	 == "hProgFPM	"))
spfpl=length(which(six$hProgFPL == "hProgFPL"))
spn=length(which(six$	hNProg== "hNProg"))

sn=length(which(six$	hNbM == "hNbM"))
snl=length(which(six$	hNbML1 == "hNbML1"))
srn=length(which(six$	hRN == "hRN"))
snll=length(which(six$hNbML5 == "hNbML5"))

sdo=length(which(six$hDA0 == "hDA0"))
sd=length(which(six$hDA1 == "hDA1"))
sdd=length(which(six$hDA2 == "hDA2"))
sg=length(which(six$hNbGaba == "hNbGaba"))
sgb=length(which(six$hGaba == "hGaba"))
sgba=length(which(six$hSert == "hSert"))
somt=length(which(six$hOMTN == "hOMTN"))


ss=length(seven$Genes)

ssb=length(which(seven$Basal == "Basal"))
sse=length(which(seven$hEndo == "hEndo"))
ssp=length(which(seven$	hPeric == "hPeric"))
ssm=length(which(seven$hMgl == "hMgl"))
sso=length(which(seven$	hOPC == "	hOPC"))

ssrc=length(which(seven$	hRgl2c == "	hRgl2c"))
ssrb=length(which(seven$hRgl2b == "hRgl2b"))
ssr=length(which(seven$hRgl3 == "hRgl3"))
ssra=length(which(seven$	hRgl2a == "hRgl2a"))
ssrr=length(which(seven$hRgl1 == "hRgl1"))

sspm=length(which(seven$hProgM == "hProgM"))
sspbp=length(which(seven$	hProgB == "hProgBP"))
sspfpm=length(which(seven$hProgFPM	 == "hProgFPM	"))
sspfpl=length(which(seven$hProgFPL == "hProgFPL"))
sspn=length(which(seven$	hNProg== "hNProg"))

ssn=length(which(seven$	hNbM == "hNbM"))
ssnl=length(which(seven$	hNbML1 == "hNbML1"))
ssrn=length(which(seven$	hRN == "hRN"))
ssnll=length(which(seven$hNbML5 == "hNbML5"))

ssdo=length(which(seven$hDA0 == "hDA0"))
ssd=length(which(seven$hDA1 == "hDA1"))
ssdd=length(which(seven$hDA2 == "hDA2"))
ssg=length(which(seven$hNbGaba == "hNbGaba"))
ssgb=length(which(seven$hGaba == "hGaba"))
ssgba=length(which(seven$hSert == "hSert"))
ssomt=length(which(seven$hOMTN == "hOMTN"))


e=length(eight$Genes)

eb=length(which(eight$Basal == "Basal"))
ee=length(which(eight$hEndo == "hEndo"))
ep=length(which(eight$	hPeric == "hPeric"))
em=length(which(eight$hMgl == "hMgl"))
eo=length(which(eight$	hOPC == "	hOPC"))

erc=length(which(eight$	hRgl2c == "	hRgl2c"))
erb=length(which(eight$hRgl2b == "hRgl2b"))
er=length(which(eight$hRgl3 == "hRgl3"))
era=length(which(eight$	hRgl2a == "hRgl2a"))
err=length(which(eight$hRgl1 == "hRgl1"))

epm=length(which(eight$hProgM == "hProgM"))
epbp=length(which(eight$	hProgB == "hProgBP"))
epfpm=length(which(eight$hProgFPM	 == "hProgFPM	"))
epfpl=length(which(eight$hProgFPL == "hProgFPL"))
epn=length(which(eight$	hNProg== "hNProg"))

en=length(which(eight$	hNbM == "hNbM"))
enl=length(which(eight$	hNbML1 == "hNbML1"))
ern=length(which(eight$	hRN == "hRN"))
enll=length(which(eight$hNbML5 == "hNbML5"))

edo=length(which(eight$hDA0 == "hDA0"))
ed=length(which(eight$hDA1 == "hDA1"))
edd=length(which(eight$hDA2 == "hDA2"))
eg=length(which(eight$hNbGaba == "hNbGaba"))
egb=length(which(eight$hGaba == "hGaba"))
egba=length(which(eight$hSert == "hSert"))
eomt=length(which(eight$hOMTN == "hOMTN"))



ne=length(nine$Genes)

neb=length(which(nine$Basal == "Basal"))
nee=length(which(nine$hEndo == "hEndo"))
nep=length(which(nine$	hPeric == "hPeric"))
nem=length(which(nine$hMgl == "hMgl"))
neo=length(which(nine$	hOPC == "	hOPC"))

nerc=length(which(nine$	hRgl2c == "	hRgl2c"))
nerb=length(which(nine$hRgl2b == "hRgl2b"))
ner=length(which(nine$hRgl3 == "hRgl3"))
nera=length(which(nine$	hRgl2a == "hRgl2a"))
nerr=length(which(nine$hRgl1 == "hRgl1"))

nepm=length(which(nine$hProgM == "hProgM"))
nepbp=length(which(nine$	hProgB == "hProgBP"))
nepfpm=length(which(nine$hProgFPM	 == "hProgFPM	"))
nepfpl=length(which(nine$hProgFPL == "hProgFPL"))
nepn=length(which(nine$	hNProg== "hNProg"))

nen=length(which(nine$	hNbM == "hNbM"))
nenl=length(which(nine$	hNbML1 == "hNbML1"))
nern=length(which(nine$	hRN == "hRN"))
nenll=length(which(nine$hNbML5 == "hNbML5"))

nedo=length(which(nine$hDA0 == "hDA0"))
ned=length(which(nine$hDA1 == "hDA1"))
nedd=length(which(nine$hDA2 == "hDA2"))
neg=length(which(nine$hNbGaba == "hNbGaba"))
negb=length(which(nine$hGaba == "hGaba"))
negba=length(which(nine$hSert == "hSert"))
neomt=length(which(nine$hOMTN == "hOMTN"))


zne=length(zero$Genes)

zneb=length(which(zero$Basal == "Basal"))
znee=length(which(zero$hEndo == "hEndo"))
znep=length(which(zero$	hPeric == "hPeric"))
znem=length(which(zero$hMgl == "hMgl"))
zneo=length(which(zero$	hOPC == "	hOPC"))

znerc=length(which(zero$	hRgl2c == "	hRgl2c"))
znerb=length(which(zero$hRgl2b == "hRgl2b"))
zner=length(which(zero$hRgl3 == "hRgl3"))
znera=length(which(zero$	hRgl2a == "hRgl2a"))
znerr=length(which(zero$hRgl1 == "hRgl1"))

znepm=length(which(zero$hProgM == "hProgM"))
znepbp=length(which(zero$	hProgB == "hProgBP"))
znepfpm=length(which(zero$hProgFPM	 == "hProgFPM	"))
znepfpl=length(which(zero$hProgFPL == "hProgFPL"))
znepn=length(which(zero$	hNProg== "hNProg"))

znen=length(which(zero$	hNbM == "hNbM"))
znenl=length(which(zero$	hNbML1 == "hNbML1"))
znern=length(which(zero$	hRN == "hRN"))
znenll=length(which(zero$hNbML5 == "hNbML5"))

znedo=length(which(zero$hDA0 == "hDA0"))
zned=length(which(zero$hDA1 == "hDA1"))
znedd=length(which(zero$hDA2 == "hDA2"))
zneg=length(which(zero$hNbGaba == "hNbGaba"))
znegb=length(which(zero$hGaba == "hGaba"))
znegba=length(which(zero$hSert == "hSert"))
zneomt=length(which(zero$hOMTN == "hOMTN"))



oneall <- c(ob,oe,op,om,oo,orc,orb,or,ora,orr,opm,opbp,opfpm,opfpl,opn,on,onl,orn,onll,odo,od,odd,og,ogb,ogba,oomt)
oneperc= oneall/o*100
twoall <- c(tb,te,tp,tm,to,trc,trb,tr,tra,trr,tpm,tpbp,tpfpm,tpfpl,tpn,tn,tnl,trn,tnll,tdo,td,tdd,tg,tgb,tgba,tomt)
twoperc= twoall/t*100
threeall<- c(bs,es,ps,ms,os,rc,rb,rs,ra,rr,pm,pbp,pfpm,pfpl,pn,ns,nl,rn,nll,do,ds,dd,gs,gb,gba,omt)
threeperc= threeall/i*100
fourall<- c(fb,fe,fp,fm,fo,frc,frb,fr,fra,frr,fpm,fpbp,fpfpm,fpfpl,fpn,fn,fnl,frn,fnll,fdo,fd,fdd,fg,fb,fgba,fomt)
fourperc= fourall/f*100
fiveall<- c(ffb,ffe,ffp,fm,ffo,ffrc,ffrb,ffr,ffra,ffrr,ffpm,ffpbp,ffpfpm,ffpfpl,ffpn,ffn,ffnl,ffrn,ffnll,ffdo,ffd,ffdd,ffg,ffb,ffgba,ffomt)
fiveperc= fiveall/ff*100
sixall<- c(sb,se,sp,sm,so,src,srb,sr,sra,srr,spm,spbp,spfpm,spfpl,spn,sn,snl,srn,snll,sdo,sd,sdd,sg,sb,sgba,somt)
sixperc= sixall/s*100
sevenall<- c(ssb,sse,ssp,ssm,sso,ssrc,ssrb,ssr,ssra,ssrr,sspm,sspbp,sspfpm,sspfpl,sspn,sn,ssnl,ssrn,ssnll,ssdo,ssd,ssdd,ssg,ssb,ssgba,ssomt)
sevenperc= sevenall/ss*100
eightall<- c(eb,ee,ep,em,eo,erc,erb,er,era,err,epm,epbp,epfpm,epfpl,epn,en,enl,ern,enll,edo,ed,edd,eg,eb,egba,eomt)
eightperc= eightall/e*100
nineall<- c(neb,nee,nep,nem,neo,nerc,nerb,ner,nera,nerr,nepm,nepbp,nepfpm,nepfpl,nepn,nen,nenl,nern,nenll,nedo,ned,nedd,neg,neb,negba,neomt)
nineperc= nineall/ne*100
zeroall<- c(zneb,znee,znep,znem,zneo,znerc,znerb,zner,znera,znerr,znepm,znepbp,znepfpm,znepfpl,znepn,znen,znenl,znern,znenll,znedo,zned,znedd,zneg,zneb,znegba,zneomt)
zeroperc= zeroall/zne*100

					
p= data.frame(oneperc, twoperc, threeperc, fourperc, fiveperc, sixperc, sevenperc, eightperc, nineperc, zeroperc)


row.names(p) <- c("Basal",	"hEndo"	, "hPeric",	"hMgl",	"hOPC",	"hRgl2c",	"hRgl2b",	"hRgl2a",	"hRgl3",	"hRgl1",	"hProgM",	"hProgBP",	"hProgFPL",	"hProgFPM",	"hNProg",	"hNbM","hNbML1","hRN","hNbML5",	"hDA0",	"hDA1",	"hDA2",	"hNbGaba",	"hGaba"	,"hSert",	"hOMTN")

  write.csv(p, file = "percentclustersall4.csv")
  
  #percentage of genes in one cluster (eg cl1) that define one cell type
  # number of genes defining BASAL/total number of genes cluster1
  
k= data.frame(oneall, twoall, threeall, fourall, fiveall, sixall, sevenall, eightall, nineall, zeroall)

row.names(k) <- c("Basal",	"hEndo"	, "hPeric",	"hMgl",	"hOPC",	"hRgl2c",	"hRgl2b",	"hRgl2a",	"hRgl3",	"hRgl1",	"hProgM",	"hProgBP",	"hProgFPL",	"hProgFPM",	"hNProg",	"hNbM","hNbML1","hRN","hNbML5",	"hDA0",	"hDA1",	"hDA2",	"hNbGaba",	"hGaba"	,"hSert",	"hOMTN")

  write.csv(k, file = "genenumberclustersall4.csv")
 

oneall <- c(ob,oe,op,om,oo,orc,orb,or,ora,orr,opm,opbp,opfpm,opfpl,opn,on,onl,orn,onll,odo,od,odd,og,ogb,ogba,oomt)
oneperc1= oneall/o
twoall <- c(tb,te,tp,tm,to,trc,trb,tr,tra,trr,tpm,tpbp,tpfpm,tpfpl,tpn,tn,tnl,trn,tnll,tdo,td,tdd,tg,tgb,tgba,tomt)
twoperc1= twoall/t
threeall<- c(bs,es,ps,ms,os,rc,rb,rs,ra,rr,pm,pbp,pfpm,pfpl,pn,ns,nl,rn,nll,do,ds,dd,gs,gb,gba,omt)
threeperc1= threeall/i
fourall<- c(fb,fe,fp,fm,fo,frc,frb,fr,fra,frr,fpm,fpbp,fpfpm,fpfpl,fpn,fn,fnl,frn,fnll,fdo,fd,fdd,fg,fb,fgba,fomt)
fourperc1= fourall/f
fiveall<- c(ffb,ffe,ffp,fm,ffo,ffrc,ffrb,ffr,ffra,ffrr,ffpm,ffpbp,ffpfpm,ffpfpl,ffpn,ffn,ffnl,ffrn,ffnll,ffdo,ffd,ffdd,ffg,ffb,ffgba,ffomt)
fiveperc1= fiveall/ff
sixall<- c(sb,se,sp,sm,so,src,srb,sr,sra,srr,spm,spbp,spfpm,spfpl,spn,sn,snl,srn,snll,sdo,sd,sdd,sg,sb,sgba,somt)
sixperc1= sixall/s
sevenall<- c(ssb,sse,ssp,ssm,sso,ssrc,ssrb,ssr,ssra,ssrr,sspm,sspbp,sspfpm,sspfpl,sspn,sn,ssnl,ssrn,ssnll,ssdo,ssd,ssdd,ssg,ssb,ssgba,ssomt)
sevenperc1= sevenall/ss
eightall<- c(eb,ee,ep,em,eo,erc,erb,er,era,err,epm,epbp,epfpm,epfpl,epn,en,enl,ern,enll,edo,ed,edd,eg,eb,egba,eomt)
eightperc1= eightall/e
nineall<- c(neb,nee,nep,nem,neo,nerc,nerb,ner,nera,nerr,nepm,nepbp,nepfpm,nepfpl,nepn,nen,nenl,nern,nenll,nedo,ned,nedd,neg,neb,negba,neomt)
nineperc1= nineall/ne
zeroall<- c(zneb,znee,znep,znem,zneo,znerc,znerb,zner,znera,znerr,znepm,znepbp,znepfpm,znepfpl,znepn,znen,znenl,znern,znenll,znedo,zned,znedd,zneg,zneb,znegba,zneomt)
zeroperc1= zeroall/zne









					
d= data.frame(oneperc1, twoperc1, threeperc1, fourperc1, fiveperc1, sixperc1, sevenperc1, eightperc1, nineperc1, zeroperc1)


row.names(d) <- c("Basal",	"hEndo"	, "hPeric",	"hMgl",	"hOPC",	"hRgl2c",	"hRgl2b",	"hRgl2a",	"hRgl3",	"hRgl1",	"hProgM",	"hProgBP",	"hProgFPL",	"hProgFPM",	"hNProg",	"hNbM","hNbML1","hRN","hNbML5",	"hDA0",	"hDA1",	"hDA2",	"hNbGaba",	"hGaba"	,"hSert",	"hOMTN")

  write.csv(d, file = "percentclustersdall4.csv")
  
  #percentage of genes in one cluster (eg cl1) that define one cell type
  # number of genes defining BASAL/total number of genes cluster1
   
  
  
  
 

oneall <- c(ob,oe,op,om,oo,orc,orb,or,ora,orr,opm,opbp,opfpm,opfpl,opn,on,onl,orn,onll,odo,od,odd,og,ogb,ogba,oomt)
oneperc2= o/oneall*100
twoall <- c(tb,te,tp,tm,to,trc,trb,tr,tra,trr,tpm,tpbp,tpfpm,tpfpl,tpn,tn,tnl,trn,tnll,tdo,td,tdd,tg,tgb,tgba,tomt)
twoperc2= t/twoall*100
threeall<- c(bs,es,ps,ms,os,rc,rb,rs,ra,rr,pm,pbp,pfpm,pfpl,pn,ns,nl,rn,nll,do,ds,dd,gs,gb,gba,omt)
threeperc2= i/threeall*100
fourall<- c(fb,fe,fp,fm,fo,frc,frb,fr,fra,frr,fpm,fpbp,fpfpm,fpfpl,fpn,fn,fnl,frn,fnll,fdo,fd,fdd,fg,fb,fgba,fomt)
fourperc2=f/fourall*100
fiveall<- c(ffb,ffe,ffp,fm,ffo,ffrc,ffrb,ffr,ffra,ffrr,ffpm,ffpbp,ffpfpm,ffpfpl,ffpn,ffn,ffnl,ffrn,ffnll,ffdo,ffd,ffdd,ffg,ffb,ffgba,ffomt)
fiveperc2= ff/fiveall*100
sixall<- c(sb,se,sp,sm,so,src,srb,sr,sra,srr,spm,spbp,spfpm,spfpl,spn,sn,snl,srn,snll,sdo,sd,sdd,sg,sb,sgba,somt)
sixperc2= s/sixall*100
sevenall<- c(ssb,sse,ssp,ssm,sso,ssrc,ssrb,ssr,ssra,ssrr,sspm,sspbp,sspfpm,sspfpl,sspn,sn,ssnl,ssrn,ssnll,ssdo,ssd,ssdd,ssg,ssb,ssgba,ssomt)
sevenperc2= ss/sevenall*100
eightall<- c(eb,ee,ep,em,eo,erc,erb,er,era,err,epm,epbp,epfpm,epfpl,epn,en,enl,ern,enll,edo,ed,edd,eg,eb,egba,eomt)
eightperc2= e/eightall*100
nineall<- c(neb,nee,nep,nem,neo,nerc,nerb,ner,nera,nerr,nepm,nepbp,nepfpm,nepfpl,nepn,nen,nenl,nern,nenll,nedo,ned,nedd,neg,neb,negba,neomt)
nineperc2= ne/nineall*100
zeroall<- c(zneb,znee,znep,znem,zneo,znerc,znerb,zner,znera,znerr,znepm,znepbp,znepfpm,znepfpl,znepn,znen,znenl,znern,znenll,znedo,zned,znedd,zneg,zneb,znegba,zneomt)
zeroperc2=zne/zeroall*100


					
e= data.frame(oneperc2, twoperc2, threeperc2, fourperc2, fiveperc2, sixperc2, sevenperc2, eightperc2, nineperc2, zeroperc2)


row.names(e) <- c("Basal",	"hEndo"	, "hPeric",	"hMgl",	"hOPC",	"hRgl2c",	"hRgl2b",	"hRgl2a",	"hRgl3",	"hRgl1",	"hProgM",	"hProgBP",	"hProgFPL",	"hProgFPM",	"hNProg",	"hNbM","hNbML1","hRN","hNbML5",	"hDA0",	"hDA1",	"hDA2",	"hNbGaba",	"hGaba"	,"hSert",	"hOMTN")

  write.csv(e, file = "percentclusterseall4.csv")
  
  #percentage of genes in one cluster (eg cl1) that define one cell type
  # number of genes defining BASAL/total number of genes cluster1
   
  
  
  
```


##Annotation of the clusters based on GeneAnalytics
```{r}
Idents(combined.all) = combined.all$seurat_clusters
combined.all <-  RenameIdents(combined.all,  `0` = "Young Neurons", `1` = "Neurons", `2` = "Neurons", `3` = "Progenitor Cells", `4` = "Glia", `5` = "Gabaergic Neurons", `6` = "Dopaminergic Neurons and Neuroblasts", `7`="Endo/Pericytes")
```